### ISSUE TITLE
Not installable for Alfred 4

### ISSUE THREAD

**Issue by alfredoperez** [urre/alfredinary#2]
I was not able to install this using Alfred4, I believe the paths to the workflow directory is different

**Comment by urre** [comment]
I use the latest version, 4.3.2 and it works fine. Where did you get stuck on installing?

**Comment by alfredoperez** [comment]
Thanks for the quick response @urre 
I got the following message. 

```
{ Error: Command failed: alfred-link
Error: Workflow directory `/Users/alfredo.perez/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows` does not exist
    at resolveAlfredPrefs.then.then.exists (/Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/alfred-link/index.js:26:11)

    at Promise.all.then.arr (/Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/execa/index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

It seems that is looking for the folder in `Alfred 3` where the folder that I have just says `Alfred`. 

![image](https://user-images.githubusercontent.com/2153583/110209415-19312000-7e52-11eb-9cd9-c039d42943ec.png)

**Comment by urre** [comment]
Ah, ok. I'll take a look

**Comment by urre** [comment]
Hey again,

There is some smaller issues with alfy, alfy-init on Alfred 4+.

Can you test this in the meantime:

1. Uninstall alfredinary `npm uninstall -g alfredinary`
2. Install 13.2 from npm `npm install -g alfredinary`
3. In the folder where alfredinary is installed on you computer (example in my case it is: `/Users/urbansanden/.nvm/versions/node/v14.8.0/lib/node_modules/alfredinary`) run this command `./node_modules/alfy/init.js`
4. If it doesn't show up in Alfred workflows, run `./node_modules/alfy/init.js` again in the same folder

**Comment by alfredoperez** [comment]
I was able to install it =)
I am seeing this error
```
{
"items": [
{
	"title": "TypeError: Cannot read property 'secure_url' of undefined",
	"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
	"valid": false,
	"text": {
		"copy": "```\nTypeError: Cannot read property 'secure_url' of undefined\n    at /Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/index.js:24:24\n    at /Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/cloudinary/lib/utils/index.js:1160:14\n    at handle_response (/Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/cloudinary/lib/uploader.js:407:7)\n    at ReadStream.<anonymous> (/Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/cloudinary/lib/uploader.js:509:7)\n```\n\n-\nAlfredinary 0.13.2\nAlfred 4.3.2\ndarwin 20.3.0",
				"largetype": "TypeError: Cannot read property 'secure_url' of undefined\n    at /Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/index.js:24:24\n    at /Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/cloudinary/lib/utils/index.js:1160:14\n    at handle_response (/Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/cloudinary/lib/uploader.js:407:7)\n    at ReadStream.<anonymous> (/Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/cloudinary/lib/uploader.js:509:7)"
	},
	"icon": {
		"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
	}
}
]
}
{
	"items": [
		{
			"title": "Error: Promise rejected with value: {\n  error: [Error: ENOENT: no such file or directory, open '/users/alfredo.perez/alfredinary/screenshot.jpg'] {\n    errno: -2,\n    code: 'ENOENT',\n    syscall: 'open',\n    path: '/users/alfredo.perez/alfredinary/screenshot.jpg'\n  }\n}\n    at Object.<anonymous> (/Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/loud-rejection/index.js:25:14)\n    at Object.emit (events.js:315:20)\n    at Object.EventEmitter.emit (domain.js:467:12)\n    at emit (/Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/signal-exit/index.js:78:11)\n    at processEmit [as emit] (/Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/signal-exit/index.js:156:5)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nError: Promise rejected with value: {\n  error: [Error: ENOENT: no such file or directory, open '/users/alfredo.perez/alfredinary/screenshot.jpg'] {\n    errno: -2,\n    code: 'ENOENT',\n    syscall: 'open',\n    path: '/users/alfredo.perez/alfredinary/screenshot.jpg'\n  }\n}\n    at Object.<anonymous> (/Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/loud-rejection/index.js:25:14)\n    at emit (/Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/signal-exit/index.js:78:11)\n    at processEmit [as emit] (/Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/signal-exit/index.js:156:5)\n```\n\n-\nAlfredinary 0.13.2\nAlfred 4.3.2\ndarwin 20.3.0",
				"largetype": "Error: Promise rejected with value: {\n  error: [Error: ENOENT: no such file or directory, open '/users/alfredo.perez/alfredinary/screenshot.jpg'] {\n    errno: -2,\n    code: 'ENOENT',\n    syscall: 'open',\n    path: '/users/alfredo.perez/alfredinary/screenshot.jpg'\n  }\n}\n    at Object.<anonymous> (/Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/loud-rejection/index.js:25:14)\n    at emit (/Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/signal-exit/index.js:78:11)\n    at processEmit [as emit] (/Users/alfredo.perez/.nvm/versions/node/v10.23.0/lib/node_modules/alfredinary/node_modules/signal-exit/index.js:156:5)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}

```

**Comment by urre** [comment]
Ok good. Yea, that now looks like env problems. Do you have Cloudinary API key and secret configured?

**Comment by alfredoperez** [comment]
yes. I do not understand the configuration for the folder and files.
It seems that it is looking for the file 
`Error: Promise rejected with value: {\n  error: [Error: ENOENT: no such file or directory, open '/users/alfredo.perez/alfredinary/screenshot.jpg'`

**Comment by urre** [comment]
Doesn't look like there is a screenshot ready to be uploaded to Cloudinary.

When you run the workflow with Alfred, you first take a screenshot with macOS, then it will save that to the temporary path/filename on your computer, you specify this in env. Then the workflow uploads this image to Cloudinary. If everything goes well you now have the Cloudinary image URL in your clipboard

**Comment by alfredoperez** [comment]
I am closing the issue since now I was able to install the plugin. I have not been able to make it work, but I think that has to be with my setup.
Thanks @urre  for the quick response and support

**Comment by urre** [comment]
@alfredoperez I'm happy to assist more so you get this working. 

Some tips:
1. Right click on the workflow and open in terminal/finder. Check so you have an `.env` file there
2. If you click this debug button on the workflow you get get more information
![](https://res.cloudinary.com/urre/image/upload/v1615270382/screenshots/oz9q6eaa73n2wushmgry.png)

**Comment by alfredoperez** [comment]
Thanks!

- I found that somehow I was not able to set the environment variables correctly.I fixed it by moving the variables directly to file 

- The error was not getting logged, because result is undefined and I changed the log to see the error
```
 function(error, result) {
    console.log(result)
    console.log(error)
    //console.log(result.secure_url);
  }
 ```

- This is the error I get
```
{
  message: 'public_id (/iehiivvzsjhh2yzounnj) is invalid',
  name: 'Error',
  http_code: 400
}
```

**Comment by urre** [comment]
Didn't quite understand. Did you get it to work then?

The idea is to have the environment variables in a `.env` in the workflow folder. Then Alfredinary can access them and use them to upload the image.

**Comment by alfredoperez** [comment]
No I did not.

The main error was while using the cloudinary uploader
```
{
  message: 'public_id (/iehiivvzsjhh2yzounnj) is invalid',
  name: 'Error',
  http_code: 400
}
```

I had to modify the[ index.js (on this line)](url) to get to the error, because it tries to do `console.log(result.secure_url);` and `result` is undefined when this error happens

**Comment by urre** [comment]
Yea, something in your Cloudinary env is not correct i believe

**Comment by xerosanyam** [comment]
I was facing same problem. this worked when I set "FOLDERNAME" ="alfred"
I guess cloudinary doesn't allow uploading to root path, that maybe causing this issue.

**Comment by urre** [comment]
@xerosanyam thanks, that is probably it yes. I'm using a foldername myself and don't have the problem. 

@alfredoperez check if this works for you!

**Comment by itsbrex** [comment]
Unable to get this working properly. Tried all of the above, but no luck.

.env is correctly set & images are saved to set folder, but nothing is uploaded.

Copy / fastest API Key + API Seceret directly, but nothing gets uploaded. Any ideas?

![Screenshot 2022-04-02 at 16 43 07](https://user-images.githubusercontent.com/9772694/161405132-c45a9045-fb79-44f4-a8f4-bcae246338e5.jpg)

Debug output shows this btw:
```
[16:40:30.965] Alfredinary[[Keyword](alfredpreferences:workflows%3Eworkflow%3Ealfredinary%3EF275466C-390F-43CC-91E5-EE1CCE836D85)] Passing output '' to [Run Script](alfredpreferences:workflows%3Eworkflow%3Ealfredinary%3E20C5478A-E10C-434A-8E5F-7F8AD206A9E7)
[16:40:32.292] Alfredinary[[Run Script](alfredpreferences:workflows%3Eworkflow%3Ealfredinary%3E20C5478A-E10C-434A-8E5F-7F8AD206A9E7)] Processing complete
[16:40:32.315] Alfredinary[[Run Script](alfredpreferences:workflows%3Eworkflow%3Ealfredinary%3E20C5478A-E10C-434A-8E5F-7F8AD206A9E7)] Passing output '' to [Run Script](alfredpreferences:workflows%3Eworkflow%3Ealfredinary%3EDBD10C76-339B-4475-8DAC-7FF19416514B)
[16:41:35.052] Alfredinary[[Run Script](alfredpreferences:workflows%3Eworkflow%3Ealfredinary%3EDBD10C76-339B-4475-8DAC-7FF19416514B)] Processing complete
[16:41:35.080] Alfredinary[[Run Script](alfredpreferences:workflows%3Eworkflow%3Ealfredinary%3EDBD10C76-339B-4475-8DAC-7FF19416514B)] Passing output '{
	"items": [
		{
			"title": "TypeError: Cannot read properties of undefined (reading 'secure_url')",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nTypeError: Cannot read properties of undefined (reading 'secure_url')\n    at /usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/index.js:24:24\n    at /usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/node_modules/cloudinary/lib/utils/index.js:1243:14\n    at handle_response (/usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/node_modules/cloudinary/lib/uploader.js:483:7)\n    at ReadStream.<anonymous> (/usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/node_modules/cloudinary/lib/uploader.js:612:7)\n    at ReadStream.emit (node:events:527:28)\n    at ReadStream.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:164:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n```\n\n-\nAlfredinary 0.13.2\nAlfred 4.6.4\ndarwin 21.4.0",
				"largetype": "TypeError: Cannot read properties of undefined (reading 'secure_url')\n    at /usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/index.js:24:24\n    at /usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/node_modules/cloudinary/lib/utils/index.js:1243:14\n    at handle_response (/usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/node_modules/cloudinary/lib/uploader.js:483:7)\n    at ReadStream.<anonymous> (/usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/node_modules/cloudinary/lib/uploader.js:612:7)\n    at ReadStream.emit (node:events:527:28)\n    at ReadStream.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:164:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
{
	"items": [
		{
			"title": "Error: Promise rejected with value: {\n  error: [Error: ENOENT: no such file or directory, open '/Users/anodigital/Screenshotsscreenshot.jpg'] {\n    errno: -2,\n    code: 'ENOENT',\n    syscall: 'open',\n    path: '/Users/anodigital/Screenshotsscreenshot.jpg'\n  }\n}\n    at Object.<anonymous> (/usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/node_modules/loud-rejection/index.js:25:14)\n    at Object.emit (node:events:527:28)\n    at Object.emit (node:domain:475:12)\n    at emit (/usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/node_modules/signal-exit/index.js:105:13)\n    at processEmit [as emit] (/usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/node_modules/signal-exit/index.js:193:7)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nError: Promise rejected with value: {\n  error: [Error: ENOENT: no such file or directory, open '/Users/anodigital/Screenshotsscreenshot.jpg'] {\n    errno: -2,\n    code: 'ENOENT',\n    syscall: 'open',\n    path: '/Users/anodigital/Screenshotsscreenshot.jpg'\n  }\n}\n    at Object.<anonymous> (/usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/node_modules/loud-rejection/index.js:25:14)\n    at Object.emit (node:events:527:28)\n    at Object.emit (node:domain:475:12)\n    at emit (/usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/node_modules/signal-exit/index.js:105:13)\n    at processEmit [as emit] (/usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/node_modules/signal-exit/index.js:193:7)\n```\n\n-\nAlfredinary 0.13.2\nAlfred 4.6.4\ndarwin 21.4.0",
				"largetype": "Error: Promise rejected with value: {\n  error: [Error: ENOENT: no such file or directory, open '/Users/anodigital/Screenshotsscreenshot.jpg'] {\n    errno: -2,\n    code: 'ENOENT',\n    syscall: 'open',\n    path: '/Users/anodigital/Screenshotsscreenshot.jpg'\n  }\n}\n    at Object.<anonymous> (/usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/node_modules/loud-rejection/index.js:25:14)\n    at Object.emit (node:events:527:28)\n    at Object.emit (node:domain:475:12)\n    at emit (/usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/node_modules/signal-exit/index.js:105:13)\n    at processEmit [as emit] (/usr/local/Cellar/node/17.8.0/lib/node_modules/alfredinary/node_modules/signal-exit/index.js:193:7)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
```

**Comment by urre** [comment]
@itsbrex not sure, how does your `.env` file look like and where is it placed?

**Comment by itsbrex** [comment]
Hey @urre I had copied / renamed the example env in place. Is is supposed to go somewhere else? 

I'll post more info when I get back to my desk.

**Comment by urre** [comment]
@itsbrex hm, can you right click the workflow inside Alfred, and select "Open in Terminal" and then do `cat .env`, do you see the correct output?
